### ISSUE TITLE
キーワード検索が動作しない

### ISSUE THREAD

**Issue by nabeta** [RCOSDP/rdms-skills#1]
検索ページのキーワード検索が動作していないようです。Webブラウザの開発ツールには、以下のエラーが表示されています。

```
Uncaught ReferenceError: csv_array_keyword is not defined
    at XMLHttpRequest.<anonymous> (search/:128:4)
```

**Comment by chikako0219** [comment]
@nabeta 
ご連絡ありがとうございます。
先ほど修正いたしましたので、ご確認いただけますでしょうか。
[https://rcosdp.github.io/rdms-skills/search/
](https://rcosdp.github.io/rdms-skills/search/
)

**Comment by nabeta** [comment]
@chikako0219 動作するようになりました。どうもありがとうございました。
